@Library('globallink')_
pipeline
{
    agent any
    stages
    {
        stage('ContiniousDownload')
        {
            steps
            {
                script
                {
                    try
                    {
                      cicd.gitDownload("Maven")  
                    }
                    catch(Exception e)
                    {
                        mail bcc: '', body: 'dev dow fail', cc: '', from: '', replyTo: '', subject: 'dev fails', to: 'admndev@gmail.com'
                    }
                }
            }
        }
        stage('contBuild')
        {
           steps
           {
               script
               {
                   cicd.newBuild()
               }
           }
        }
        stage('contDeploy')
        {
            steps
            {
                script
                {
                    cicd.newDeployment("shared2","172.31.8.235","uat")
                }
            }
        }
        stage('ContTesting')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("functionaltesting")
                    cicd.runselenium("shared2")
                }
            }
        }
        stage('contDeli')
        {
            steps
            {
                script
                {
                    cicd.newDeployment("shared2","172.31.1.26","prodc")
                }
            }
        }
    }
}
